export default {
  GET_STARSHIP_DETAILS: "starships/", // ID IS HARDCODED TO THE URL ITSELF, for example purpose
  USER_LOGIN: "/admin/auth/login",
  LOGOUT: "/admin/auth/logout",
  USER_LOGIN_QR: "/admin/auth/login-qr",
  RESEND_QR: "/admin/auth/resend-qr",
  FORGOT_PASSWORD: "/admin/auth/forgotPassword",
  CREATE_NEW_PASSWORD: "/admin/auth/resetPassword",
  PHARMACIES: "/admin/store",
  BUSINESSES: "admin/business",
  NOTIFICATIONS: "/admin/auth/notifications",
  ORDERS: "/admin/orders",
  MEMBERS: "admin/member",
  ORDERS_REPORTING: "/admin/stats/total-orders",
  MONTHLY_REPORT: "/admin/stats/sale-report",
  TOP_SELLING_PRODUCTS: "/admin/stats/top-selling-prdoucts",
  ORDER_DETAIL: "/admin/orders",
  PRODUCTS: "/admin/products",
  PRODUCT_DETAIL: "/admin/products/",
  PRODUCT_INVENTORIES: "/admin/products/product/",
  STORES: "/admin/store/stores/",
  ACTIVE_BUSINESS: "/admin/business/active",
};
